# Generated by Django 3.0.3 on 2020-09-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.CharField(choices=[('CRM', 'Crime/Mystery'), ('ADN', 'Adventure'), ('EDU', 'Educational'), ('MOT', 'Motivational'), ('BGR', 'Biography'), ('FIC', 'Fiction')], default='FIC', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='book_frontpage',
            field=models.ImageField(default='default.jpg', upload_to='book_frontpages'),
        ),
    ]
