# Generated by Django 3.0.3 on 2020-11-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='Abc', max_length=100),
        ),
    ]
