# Generated by Django 3.0.3 on 2020-11-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0005_auto_20201103_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_isbn',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='order_placed_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('ACP', 'Accepted'), ('SHP', 'Shipped'), ('OFD', 'Out For Delivery'), ('DEL', 'Delivered'), ('CAN', 'Cancelled')], default='PEN', max_length=30),
        ),
    ]
